### ISSUE TITLE
Server crash on gunpowder block ignition

### ISSUE THREAD

**Issue by laxotor** [TrueCP6/PolyPack#1]
[crash-2020-12-01_11.19.26-server.txt](https://github.com/TrueCP6/PolyPack/files/5619965/crash-2020-12-01_11.19.26-server.txt)

[latest.log](https://github.com/TrueCP6/PolyPack/files/5619992/latest.log)

When the gunpowder block is ignited, the server cras

**Comment by TrueCP6** [comment]
The same happens in a server with only Blast and Fabric API. [Ladysnake/BLAST#9](https://github.com/Ladysnake/BLAST/issues/9)
