### ISSUE TITLE
How can I update a PolyPack server to the latest version of Minecraft?

### ISSUE THREAD

**Issue by Username-Is-Unavailabl** [TrueCP6/PolyPack#4]

**Comment by TrueCP6** [comment]
Change `1.16.4` to `1.16.5` in `download-fabric.bat` change and run `download-fabric.bat`.

**Comment by Username-Is-Unavailabl** [comment]
I have tried this and when I start the server it still says: `Loading for game Minecraft 1.16.4`

**Comment by Username-Is-Unavailabl** [comment]
Thanks!
I will also update the mods to 1.16.5
